CREATE TABLE jurnal (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    judul VARCHAR(150) NOT NULL,
    penerbit VARCHAR(100) NOT NULL,
    tahun_terbit INTEGER NOT NULL
);

CREATE TABLE program_studi (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode VARCHAR(25) NOT NULL UNIQUE,
    nama VARCHAR(100) NOT NULL,
    jenjang VARCHAR(5) NOT NULL
);

CREATE TABLE kurikulum (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode VARCHAR(25) NOT NULL UNIQUE,
    tahun_berlaku INTEGER NOT NULL,
    status VARCHAR(10) NOT NULL,
    id_prodi INTEGER NOT NULL,
    CONSTRAINT fk_kurikulum_prodi FOREIGN KEY (id_prodi) REFERENCES program_studi (id)
);

CREATE INDEX idx_kurikulum_prodi ON kurikulum (id_prodi);
