CREATE TABLE dosen (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nip VARCHAR(30) NOT NULL UNIQUE,
    nama VARCHAR(100) NOT NULL
);

CREATE TABLE mata_kuliah (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode VARCHAR(25) NOT NULL UNIQUE,
    nama VARCHAR(100) NOT NULL,
    sks_teori INTEGER NOT NULL,
    sks_praktikum INTEGER NOT NULL,
    id_kurikulum INTEGER NOT NULL,
    CONSTRAINT fk_mk_kurikulum FOREIGN KEY (id_kurikulum) REFERENCES kurikulum (id)
);

CREATE TABLE pengampu (
    id_mata_kuliah INTEGER NOT NULL,
    id_dosen INTEGER NOT NULL,
    PRIMARY KEY (id_mata_kuliah, id_dosen),
    CONSTRAINT fk_pengampu_mk FOREIGN KEY (id_mata_kuliah) REFERENCES mata_kuliah (id) ON DELETE CASCADE,
    CONSTRAINT fk_pengampu_dosen FOREIGN KEY (id_dosen) REFERENCES dosen (id)
);

CREATE INDEX idx_mk_kurikulum ON mata_kuliah (id_kurikulum);