CREATE TABLE kategori (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE pengumuman (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    judul VARCHAR(200) NOT NULL UNIQUE,
    isi TEXT NOT NULL,
    tanggal_terbit DATE NOT NULL,
    jumlah_dilihat INTEGER NOT NULL DEFAULT 0,
    id_kategori INTEGER NOT NULL,
    CONSTRAINT fk_pengumuman_kategori FOREIGN KEY (id_kategori) REFERENCES kategori (id)
);
CREATE INDEX idx_pengumuman_kategori ON pengumuman (id_kategori);

CREATE TABLE lampiran (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_berkas VARCHAR(255) NOT NULL,
    ukuran INTEGER NOT NULL,
    id_pengumuman INTEGER NOT NULL,
    CONSTRAINT fk_lampiran_pengumuman FOREIGN KEY (id_pengumuman) REFERENCES pengumuman (id) ON DELETE CASCADE
);
CREATE INDEX idx_lampiran_pengumuman ON lampiran (id_pengumuman);

CREATE TABLE pengumuman_prodi (
    id_pengumuman INTEGER NOT NULL,
    id_prodi INTEGER NOT NULL,
    PRIMARY KEY (id_pengumuman, id_prodi),
    CONSTRAINT fk_pp_pengumuman FOREIGN KEY (id_pengumuman) REFERENCES pengumuman (id) ON DELETE CASCADE,
    CONSTRAINT fk_pp_prodi FOREIGN KEY (id_prodi) REFERENCES program_studi (id) ON DELETE CASCADE
);